neodev_anubisbb_api:
    path: /anubis/api/{name}
    defaults: { _controller: neodev.anubisbb.controller.api:handler, name: "" }

neodev_anubisbb_pages:
    path: /anubis/pages/{name}
    defaults: { _controller: neodev.anubisbb.controller.pages:handler, name: "" }
